//! Embedded sample data: the TR-606 multisample banks (8 hits each) and the
//! long Rift textures ([221]).
//!
//! Each WAV (float32 mono, 44.1 kHz) holds the 8 hits back to back at even
//! spacing. Files are embedded with `include_bytes!` and decoded once into
//! global `OnceLock`s. Playback handles the session sample-rate conversion
//! through fractional-position interpolation, so no resampling pass is
//! needed at load time.
//!
//! A **texture** ([221]) is the other shape the same decoder serves: one
//! continuous buffer of several seconds instead of eight slices, which Rift
//! reads from an arbitrary offset. Same embedding, same `OnceLock`, same
//! fractional-position playback — only the splitting differs, so the RIFF
//! parser is shared (`decode_wav`).
//!
//! Real-time contract: banks and textures must be pre-warmed from
//! `DrumSynthesizer::initialize_with_layout` (non-RT). After that, calls from
//! the audio thread are a single atomic load — no allocation, no lock.

use std::sync::{Arc, OnceLock};

pub const HIT_COUNT: usize = 8;

static BD606_BYTES: &[u8] = include_bytes!("../../assets/bd606.wav");
static SD606_BYTES: &[u8] = include_bytes!("../../assets/sd606.wav");
static CH606_BYTES: &[u8] = include_bytes!("../../assets/ch606.wav");
static OH606_BYTES: &[u8] = include_bytes!("../../assets/oh606.wav");

pub struct SampleBank {
    pub source_rate: f32,
    pub hits: [Vec<f32>; HIT_COUNT],
}

static BD606_BANK: OnceLock<SampleBank> = OnceLock::new();
static SD606_BANK: OnceLock<SampleBank> = OnceLock::new();
static CH606_BANK: OnceLock<SampleBank> = OnceLock::new();
static OH606_BANK: OnceLock<SampleBank> = OnceLock::new();

/// TR-606 bass drum bank (8 × 1 s hits).
pub fn bd606() -> &'static SampleBank {
    BD606_BANK.get_or_init(|| load_bank(BD606_BYTES))
}

/// TR-606 snare bank (8 × 0.5 s hits).
pub fn sd606() -> &'static SampleBank {
    SD606_BANK.get_or_init(|| load_bank(SD606_BYTES))
}

/// TR-606 closed hi-hat bank (8 × 0.5 s hits).
pub fn ch606() -> &'static SampleBank {
    CH606_BANK.get_or_init(|| load_bank(CH606_BYTES))
}

/// TR-606 OPEN hi-hat bank (8 × 1 s hits — an open hat rings longer, so the
/// slices are twice as long as the closed one's).
pub fn oh606() -> &'static SampleBank {
    OH606_BANK.get_or_init(|| load_bank(OH606_BYTES))
}

// ---------------------------------------------------------------------------
// Rift textures ([221])
// ---------------------------------------------------------------------------

pub const TEXTURE_COUNT: usize = 4;

/// Generated by `tools/gen_textures.py` (fixed seed, so re-running it
/// reproduces these files byte for byte). Mono PCM 16-bit, 44.1 kHz, 6 s —
/// half the weight of the float32 606 banks for the same duration.
static TEXTURE_BYTES: [&[u8]; TEXTURE_COUNT] = [
    include_bytes!("../../assets/textures/noise-field.wav"),
    include_bytes!("../../assets/textures/metal.wav"),
    include_bytes!("../../assets/textures/crackle.wav"),
    include_bytes!("../../assets/textures/sweep.wav"),
];

/// Columns in the drawn waveform summary. The Sound Panel graph is ~200 px
/// wide, so this is already finer than it can show.
pub const TEXTURE_PEAK_COLUMNS: usize = 512;

/// One long buffer to read from at an arbitrary offset, as opposed to
/// `SampleBank`'s eight fixed slices.
pub struct TextureBank {
    pub source_rate: f32,
    /// The material: mono, or the LEFT channel of a stereo user file.
    pub data: Vec<f32>,
    /// [228] The RIGHT channel of a stereo user file, same length as `data`;
    /// `None` for mono files and every embedded texture. With Rift's Stereo
    /// switch off the two are mixed at read time.
    pub right: Option<Vec<f32>>,
    /// (min, max) per column — the waveform the panel draws. Computed once at
    /// decode time: scanning half a million samples on every UI frame would
    /// cost far more than the picture is worth.
    pub peaks: Vec<(f32, f32)>,
}

fn peak_summary(data: &[f32]) -> Vec<(f32, f32)> {
    if data.is_empty() {
        return vec![(0.0, 0.0); TEXTURE_PEAK_COLUMNS];
    }
    (0..TEXTURE_PEAK_COLUMNS)
        .map(|c| {
            let from = c * data.len() / TEXTURE_PEAK_COLUMNS;
            let to = ((c + 1) * data.len() / TEXTURE_PEAK_COLUMNS).max(from + 1);
            let slice = &data[from..to.min(data.len())];
            let lo = slice.iter().cloned().fold(f32::MAX, f32::min);
            let hi = slice.iter().cloned().fold(f32::MIN, f32::max);
            (lo, hi)
        })
        .collect()
}

static TEXTURE_BANKS: [OnceLock<TextureBank>; TEXTURE_COUNT] =
    [const { OnceLock::new() }; TEXTURE_COUNT];

/// Texture `index`, clamped into range — an out-of-range index must yield a
/// usable texture, never a panic on the audio thread.
pub fn texture(index: usize) -> &'static TextureBank {
    let i = index.min(TEXTURE_COUNT - 1);
    TEXTURE_BANKS[i].get_or_init(|| {
        let (source_rate, data) = decode_wav(TEXTURE_BYTES[i]);
        let peaks = peak_summary(&data);
        TextureBank {
            source_rate,
            data,
            right: None,
            peaks,
        }
    })
}

/// Decode every texture. Call from `initialize_with_layout` only (non-RT):
/// `create_voice_for_kind` runs on the audio thread and must not allocate.
pub fn prewarm_textures() {
    for i in 0..TEXTURE_COUNT {
        let _ = texture(i);
    }
}

// ---------------------------------------------------------------------------
// User textures ([228])
// ---------------------------------------------------------------------------

/// One custom texture per LANE ([228]): the pool has one slot per track, and
/// a lane's Texture menu ends with that lane's own file.
pub const LANE_TEXTURE_SLOTS: usize = crate::track::MAX_TRACKS;
/// Index of the "Custom" entry in the Texture menu: the embedded textures,
/// then the lane's file.
pub const CUSTOM_TEXTURE_INDEX: usize = TEXTURE_COUNT;
/// Entries in the Texture menu.
pub const TEXTURE_OPTION_COUNT: usize = TEXTURE_COUNT + 1;
/// Longest custom texture kept, in seconds - 60 s at 48 kHz is 11.5 MB of f32
/// per lane, and the offset slider gets no more precise past that anyway.
pub const USER_TEXTURE_MAX_SECS: f32 = 60.0;

/// The per-instance pool of lane textures. The UI (or the state restore)
/// publishes decoded files; the audio thread reads a lane's slot with ONE
/// atomic load plus an `Arc` clone (`arc_swap`), no lock, no allocation.
///
/// Memory discipline: a replaced texture is parked in `previous` on the UI side
/// for one more generation, so the voice that may still be reading it never
/// holds the last reference - freeing on the audio thread is what that would
/// mean. It is freed on the NEXT publish into the same lane, on the UI thread.
pub struct TexturePool {
    slots: [arc_swap::ArcSwapOption<TextureBank>; LANE_TEXTURE_SLOTS],
    previous: std::sync::Mutex<[Option<Arc<TextureBank>>; LANE_TEXTURE_SLOTS]>,
}

impl Default for TexturePool {
    fn default() -> Self {
        Self::new()
    }
}

impl TexturePool {
    pub fn new() -> Self {
        Self {
            slots: std::array::from_fn(|_| arc_swap::ArcSwapOption::from(None)),
            previous: std::sync::Mutex::new(std::array::from_fn(|_| None)),
        }
    }

    /// UI / main thread only: install (or remove) a lane's texture.
    pub fn publish(&self, lane: usize, bank: Option<Arc<TextureBank>>) {
        if lane >= LANE_TEXTURE_SLOTS {
            return;
        }
        let old = self.slots[lane].swap(bank);
        if let Ok(mut previous) = self.previous.lock() {
            previous[lane] = old;
        }
    }

    /// Audio thread: the lane's texture, held alive by the returned `Arc`.
    pub fn get(&self, lane: usize) -> Option<Arc<TextureBank>> {
        self.slots.get(lane)?.load_full()
    }

    pub fn is_loaded(&self, lane: usize) -> bool {
        self.slots
            .get(lane)
            .map(|s| s.load().is_some())
            .unwrap_or(false)
    }
}

/// What a Rift voice reads during one hit: an embedded texture, or a user one
/// held alive for as long as the hit lasts.
pub enum TextureSource {
    Embedded(&'static TextureBank),
    User(Arc<TextureBank>),
}

impl TextureSource {
    pub fn bank(&self) -> &TextureBank {
        match self {
            TextureSource::Embedded(bank) => bank,
            TextureSource::User(bank) => bank,
        }
    }
}

/// Resolve a Texture-menu index for one lane: the embedded textures, or the
/// lane's own file ("Custom", `lane` = the pool and the lane's slot). A lane
/// with no file - never loaded, gone missing, unreadable - falls back to the
/// first embedded texture: a hit must never go silent for want of a file.
/// Out-of-range indices clamp into the menu.
pub fn resolve_texture(index: usize, lane: Option<(&TexturePool, usize)>) -> TextureSource {
    let index = index.min(TEXTURE_OPTION_COUNT - 1);
    if index < TEXTURE_COUNT {
        return TextureSource::Embedded(texture(index));
    }
    match lane.and_then(|(pool, slot)| pool.get(slot)) {
        Some(bank) => TextureSource::User(bank),
        None => TextureSource::Embedded(texture(0)),
    }
}

/// Decode a WAV file from disk into a texture: any integer depth or float,
/// capped at `USER_TEXTURE_MAX_SECS`. A stereo file keeps its two channels
/// (`data` = left, `right` = right) so Rift's Stereo switch can play them as
/// they are; more than two channels are averaged to mono. Never called on
/// the audio thread. Errors are for the UI to show.
pub fn load_texture_file(path: &std::path::Path) -> Result<TextureBank, String> {
    let mut reader = hound::WavReader::open(path).map_err(|e| e.to_string())?;
    let spec = reader.spec();
    let channels = spec.channels.max(1) as usize;
    if spec.sample_rate == 0 {
        return Err("sample rate of 0".to_string());
    }
    let max_frames = (USER_TEXTURE_MAX_SECS * spec.sample_rate as f32) as usize;
    let frames = (reader.len() as usize / channels).min(max_frames);

    // Interleaved samples as f32, whatever the file's format.
    let mut interleaved: Vec<f32> = Vec::with_capacity(frames * channels);
    match spec.sample_format {
        hound::SampleFormat::Float => {
            for sample in reader.samples::<f32>().take(frames * channels) {
                interleaved.push(sample.map_err(|e| e.to_string())?);
            }
        }
        hound::SampleFormat::Int => {
            let bits = spec.bits_per_sample.clamp(1, 32);
            let scale = 1.0 / (1u64 << (bits - 1)) as f32;
            for sample in reader.samples::<i32>().take(frames * channels) {
                interleaved.push(sample.map_err(|e| e.to_string())? as f32 * scale);
            }
        }
    }
    let frames = interleaved.len() / channels;
    if frames < 4 {
        return Err("no audio in the file".to_string());
    }

    let (data, right) = if channels == 2 {
        let left: Vec<f32> = interleaved.iter().step_by(2).copied().collect();
        let right: Vec<f32> = interleaved.iter().skip(1).step_by(2).copied().collect();
        (left, Some(right))
    } else {
        let inv = 1.0 / channels as f32;
        let mono: Vec<f32> = interleaved
            .chunks_exact(channels)
            .map(|frame| frame.iter().sum::<f32>() * inv)
            .collect();
        (mono, None)
    };
    // The picture is the mono mix, whatever the switch says.
    let peaks = match &right {
        Some(r) => {
            let mix: Vec<f32> = data.iter().zip(r).map(|(l, r)| 0.5 * (l + r)).collect();
            peak_summary(&mix)
        }
        None => peak_summary(&data),
    };
    Ok(TextureBank {
        source_rate: spec.sample_rate as f32,
        data,
        right,
        peaks,
    })
}

fn read_u16_le(bytes: &[u8], off: usize) -> Option<u16> {
    Some(u16::from_le_bytes([*bytes.get(off)?, *bytes.get(off + 1)?]))
}

fn read_u32_le(bytes: &[u8], off: usize) -> Option<u32> {
    Some(u32::from_le_bytes([
        *bytes.get(off)?,
        *bytes.get(off + 1)?,
        *bytes.get(off + 2)?,
        *bytes.get(off + 3)?,
    ]))
}

/// Decode an embedded RIFF/WAVE file to mono f32 samples plus its sample rate.
///
/// Handles the two formats we ship: IEEE float 32-bit and PCM 16-bit. On a
/// multi-channel file only the first channel is read. Anything else decodes to
/// an empty buffer — the voice then stays inert instead of panicking.
fn decode_wav(bytes: &[u8]) -> (f32, Vec<f32>) {
    let is_riff = bytes.len() >= 12 && &bytes[0..4] == b"RIFF" && &bytes[8..12] == b"WAVE";

    let mut source_rate = 44100u32;
    let mut audio_format = 3u16; // IEEE float
    let mut channels = 1u16;
    let mut bits_per_sample = 32u16;
    let mut data: Option<(usize, usize)> = None; // (offset, len)

    if is_riff {
        let mut pos = 12usize;
        while pos + 8 <= bytes.len() {
            let id = &bytes[pos..pos + 4];
            let size = read_u32_le(bytes, pos + 4).unwrap_or(0) as usize;
            let body = pos + 8;
            if body + size > bytes.len() {
                break;
            }
            match id {
                b"fmt " => {
                    audio_format = read_u16_le(bytes, body).unwrap_or(3);
                    channels = read_u16_le(bytes, body + 2).unwrap_or(1);
                    source_rate = read_u32_le(bytes, body + 4).unwrap_or(44100);
                    bits_per_sample = read_u16_le(bytes, body + 14).unwrap_or(32);
                }
                b"data" => {
                    data = Some((body, size));
                    break;
                }
                _ => {}
            }
            pos = body + size + (size & 1);
        }
    }

    let samples: Vec<f32> = match data {
        Some((off, len)) if audio_format == 3 && bits_per_sample == 32 => {
            let frame = 4 * channels.max(1) as usize;
            (0..len / frame)
                .map(|i| {
                    let o = off + i * frame;
                    f32::from_le_bytes([bytes[o], bytes[o + 1], bytes[o + 2], bytes[o + 3]])
                })
                .collect()
        }
        Some((off, len)) if audio_format == 1 && bits_per_sample == 16 => {
            let frame = 2 * channels.max(1) as usize;
            (0..len / frame)
                .map(|i| {
                    let o = off + i * frame;
                    i16::from_le_bytes([bytes[o], bytes[o + 1]]) as f32 / 32768.0
                })
                .collect()
        }
        // Unparseable file: fall back to silence so the voice stays inert
        // instead of panicking on host-supplied-adjacent data.
        _ => Vec::new(),
    };

    (source_rate as f32, samples)
}

fn load_bank(bytes: &[u8]) -> SampleBank {
    let (source_rate, samples) = decode_wav(bytes);
    let hit_len = samples.len() / HIT_COUNT;
    let hits: [Vec<f32>; HIT_COUNT] = std::array::from_fn(|h| {
        if hit_len == 0 {
            Vec::new()
        } else {
            samples[h * hit_len..(h + 1) * hit_len].to_vec()
        }
    });

    SampleBank { source_rate, hits }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn check_bank(bank: &SampleBank, expected_hit_len: usize) {
        assert_eq!(bank.source_rate, 44100.0);
        for (i, hit) in bank.hits.iter().enumerate() {
            assert_eq!(hit.len(), expected_hit_len, "hit {i} length");
            let peak = hit.iter().map(|s| s.abs()).fold(0.0f32, f32::max);
            assert!(peak > 0.1, "hit {i} is silent (peak {peak})");
        }
    }

    #[test]
    fn bd606_bank_decodes_eight_nonempty_hits() {
        check_bank(bd606(), 44100);
    }

    #[test]
    fn sd606_bank_decodes_eight_nonempty_hits() {
        check_bank(sd606(), 22050);
    }

    /// The textures are what Rift plays; a silent or truncated one would make
    /// the instrument look broken for a reason invisible in its own code.
    #[test]
    fn every_texture_decodes_long_and_loud() {
        for i in 0..TEXTURE_COUNT {
            let t = texture(i);
            assert_eq!(t.source_rate, 44100.0, "texture {i} sample rate");
            assert!(
                t.data.len() > 44100 * 4,
                "texture {i} is only {} samples - expected several seconds",
                t.data.len()
            );
            let peak = t.data.iter().map(|s| s.abs()).fold(0.0f32, f32::max);
            assert!(peak > 0.5, "texture {i} peaks at {peak}");
            assert!(t.data.iter().all(|s| s.is_finite()), "texture {i} has non-finite samples");
        }
    }

    /// Rift reads an arbitrary offset, so no long stretch may be dead: a slice
    /// taken there would be a silent hit.
    #[test]
    fn no_texture_has_a_silent_stretch() {
        let win = 4410; // 100 ms
        for i in 0..TEXTURE_COUNT {
            let data = &texture(i).data;
            for (w, chunk) in data.chunks(win).enumerate() {
                let rms = (chunk.iter().map(|s| s * s).sum::<f32>() / chunk.len() as f32).sqrt();
                assert!(rms > 0.001, "texture {i} window {w} is silent (rms {rms})");
            }
        }
    }

    /// The drawn summary must have one column per slot and follow the audio.
    #[test]
    fn every_texture_summarises_into_peaks() {
        for i in 0..TEXTURE_COUNT {
            let t = texture(i);
            assert_eq!(t.peaks.len(), TEXTURE_PEAK_COLUMNS, "texture {i} column count");
            assert!(
                t.peaks.iter().all(|(lo, hi)| lo <= hi && lo.is_finite() && hi.is_finite()),
                "texture {i} has a broken column"
            );
            let tallest = t.peaks.iter().map(|(lo, hi)| hi - lo).fold(0.0f32, f32::max);
            assert!(tallest > 0.5, "texture {i} summary is flat ({tallest})");
        }
    }

    /// An out-of-range index must clamp rather than panic: it reaches here from
    /// persisted plock and preset data.
    #[test]
    fn texture_index_is_clamped() {
        assert_eq!(texture(99).data.len(), texture(TEXTURE_COUNT - 1).data.len());
    }

    // ── [228] user textures ─────────────────────────────────────────────────

    fn sine_bank(hz: f32, secs: f32, rate: f32) -> TextureBank {
        let n = (secs * rate) as usize;
        let data: Vec<f32> = (0..n)
            .map(|i| (i as f32 * hz * std::f32::consts::TAU / rate).sin() * 0.5)
            .collect();
        let peaks = peak_summary(&data);
        TextureBank { source_rate: rate, data, right: None, peaks }
    }

    #[test]
    fn pool_publishes_and_resolves_with_a_fallback_for_empty_slots() {
        let pool = TexturePool::new();
        // Embedded indices never touch the pool.
        assert!(matches!(resolve_texture(1, Some((&pool, 2))), TextureSource::Embedded(_)));
        // A lane without a file plays the first embedded texture.
        match resolve_texture(CUSTOM_TEXTURE_INDEX, Some((&pool, 2))) {
            TextureSource::Embedded(bank) => assert!(std::ptr::eq(bank, texture(0))),
            TextureSource::User(_) => panic!("empty lane must fall back"),
        }
        // A loaded lane is what plays, held by an Arc - and only that lane.
        pool.publish(2, Some(Arc::new(sine_bank(440.0, 0.1, 8000.0))));
        assert!(pool.is_loaded(2));
        match resolve_texture(CUSTOM_TEXTURE_INDEX, Some((&pool, 2))) {
            TextureSource::User(bank) => assert_eq!(bank.data.len(), 800),
            TextureSource::Embedded(_) => panic!("loaded lane must be used"),
        }
        assert!(matches!(resolve_texture(CUSTOM_TEXTURE_INDEX, Some((&pool, 3))), TextureSource::Embedded(_)));
        // Replacing keeps the old one parked (never freed on the reader's side).
        let old = pool.get(2).unwrap();
        pool.publish(2, Some(Arc::new(sine_bank(220.0, 0.2, 8000.0))));
        assert!(Arc::strong_count(&old) >= 2, "previous generation must be parked");
        pool.publish(2, None);
        assert!(!pool.is_loaded(2));
        // Out of range: no pool access, clamps into the menu.
        assert!(matches!(resolve_texture(999, None), TextureSource::Embedded(_)));
    }

    #[test]
    fn user_wav_files_decode_to_mono_at_their_own_rate_and_are_capped() {
        let dir = std::env::temp_dir().join(format!("flash-drum-tex-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();

        // Stereo 24-bit at 22.05 kHz: left = +0.5, right = -0.25 -> mono 0.125.
        let stereo = dir.join("stereo24.wav");
        {
            let spec = hound::WavSpec {
                channels: 2,
                sample_rate: 22050,
                bits_per_sample: 24,
                sample_format: hound::SampleFormat::Int,
            };
            let mut w = hound::WavWriter::create(&stereo, spec).unwrap();
            let full = (1i32 << 23) as f32;
            for _ in 0..1000 {
                w.write_sample((0.5 * full) as i32).unwrap();
                w.write_sample((-0.25 * full) as i32).unwrap();
            }
            w.finalize().unwrap();
        }
        let bank = load_texture_file(&stereo).expect("decodes");
        assert_eq!(bank.source_rate, 22050.0);
        assert_eq!(bank.data.len(), 1000);
        // Both channels kept: left in `data`, right in `right`; the picture
        // is their mix.
        assert!((bank.data[10] - 0.5).abs() < 1e-3, "{}", bank.data[10]);
        let right = bank.right.as_ref().expect("stereo file keeps its right channel");
        assert_eq!(right.len(), 1000);
        assert!((right[10] + 0.25).abs() < 1e-3, "{}", right[10]);
        assert_eq!(bank.peaks.len(), TEXTURE_PEAK_COLUMNS);
        assert!((bank.peaks[100].1 - 0.125).abs() < 1e-3, "{:?}", bank.peaks[100]);

        // Float mono, longer than the cap at a low rate: truncated to the cap.
        let long = dir.join("long.wav");
        {
            let spec = hound::WavSpec {
                channels: 1,
                sample_rate: 1000,
                bits_per_sample: 32,
                sample_format: hound::SampleFormat::Float,
            };
            let mut w = hound::WavWriter::create(&long, spec).unwrap();
            for i in 0..(USER_TEXTURE_MAX_SECS as usize * 1000 + 5000) {
                w.write_sample((i % 7) as f32 * 0.1).unwrap();
            }
            w.finalize().unwrap();
        }
        let bank = load_texture_file(&long).expect("decodes");
        assert_eq!(bank.data.len(), USER_TEXTURE_MAX_SECS as usize * 1000);
        assert!(bank.right.is_none(), "a mono file has no right channel");

        // Not a WAV: an error, not a panic.
        let junk = dir.join("junk.wav");
        std::fs::write(&junk, b"not a riff file at all").unwrap();
        assert!(load_texture_file(&junk).is_err());
        assert!(load_texture_file(&dir.join("missing.wav")).is_err());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn each_hit_starts_with_an_attack() {
        for bank in [bd606(), sd606()] {
            for (i, hit) in bank.hits.iter().enumerate() {
                let head = hit[..4410].iter().map(|s| s.abs()).fold(0.0f32, f32::max);
                assert!(head > 0.1, "hit {i} has no attack in its first 100 ms");
            }
        }
    }
}
