#!/usr/bin/env python3
"""[277] Build THIRD-PARTY-LICENSES.txt: the full license texts of every crate
compiled into the Windows plugin, plus the embedded fonts and the ported AC606
code. MIT, ISC, Apache, OFL... ask for their text to travel with the binary;
the installer and the VST3 bundle ship this file.

Run from anywhere, before a release (the file is committed):

    python tools/gen_third_party_licenses.py

Same Cargo.lock -> same file. Texts shared by several crates appear once.
"""
import hashlib
import json
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
CRATE_DIR = ROOT / "drum-pattern-vst"
MANIFEST = CRATE_DIR / "Cargo.toml"
OUT = ROOT / "THIRD-PARTY-LICENSES.txt"
GPL = ROOT / "LICENSE"
TARGET = "x86_64-pc-windows-msvc"  # what build.ps1 ships

LICENSE_NAME = re.compile(
    r"^(licen[cs]e|copying|notice|unlicense|copyright)([-_. ].*)?$", re.IGNORECASE
)

# Assets compiled into the binary that are not crates.
EXTRA = [
    ("IBM Plex Sans / IBM Plex Mono (embedded fonts)", CRATE_DIR / "assets" / "fonts" / "LICENSE-IBM-Plex.txt"),
    (
        "AC606 voices, ported from analogcode's 606-Inspired-Synth-Drums (src/synthesis/ac606/)",
        CRATE_DIR / "src" / "synthesis" / "ac606" / "LICENSE-MIT.txt",
    ),
]


def cargo(*args):
    return subprocess.run(
        ["cargo", *args, "--manifest-path", str(MANIFEST), "--locked"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
    ).stdout


def read(path):
    text = path.read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n")
    return "\n".join(l.rstrip() for l in text.strip("\n").split("\n"))


def license_files(pkg):
    """The crate's license files; for a crate inside a workspace (vendored
    nih-plug, git checkouts) that ships none of its own, the workspace's."""
    found = []
    if pkg.get("license_file"):
        f = pathlib.Path(pkg["manifest_path"]).parent / pkg["license_file"]
        if f.is_file():
            found.append(f)
    d = pathlib.Path(pkg["manifest_path"]).parent
    for _ in range(3):
        found += sorted(f for f in d.iterdir() if f.is_file() and LICENSE_NAME.match(f.name))
        fonts = d / "fonts"
        if fonts.is_dir():  # egui's default fonts carry their own licenses
            found += sorted(fonts.glob("*.txt"))
        if found or d.parent == d or d == CRATE_DIR or d.parent.name in ("src", "checkouts"):
            break
        d = d.parent
    unique = []
    for f in found:
        if f not in unique:
            unique.append(f)
    return unique


def main():
    used = set()
    for line in cargo("tree", "--target", TARGET, "-e", "normal", "--prefix", "none", "--format", "{p}").splitlines():
        m = re.match(r"^(\S+) v(\S+)", line.strip())
        if m:
            used.add((m.group(1), m.group(2)))
    meta = json.loads(cargo("metadata", "--format-version", "1"))
    gpl_text = read(GPL)

    groups = {}  # text hash -> {"text", "users", "files"}
    missing = []
    for pkg in sorted(meta["packages"], key=lambda p: (p["name"], p["version"])):
        if (pkg["name"], pkg["version"]) not in used or pkg["name"] == "drum-pattern-vst":
            continue
        label = f'{pkg["name"]} {pkg["version"]}'
        if pkg.get("license"):
            label += f' ({pkg["license"]})'
        files = license_files(pkg)
        if not files:
            missing.append(label)
            continue
        for f in files:
            text = read(f)
            key = hashlib.sha256(text.encode("utf-8")).hexdigest()
            g = groups.setdefault(key, {"text": text, "users": [], "files": set()})
            if label not in g["users"]:
                g["users"].append(label)
            g["files"].add(f.name)

    out = [
        "FLASH DRUM - THIRD-PARTY LICENSES",
        "=================================",
        "",
        "Flash Drum is distributed under the GNU General Public License v3",
        "(LICENSE.txt). It contains the third-party components below, whose",
        "licenses ask for these texts to be distributed with it.",
        "",
        f"Generated by tools/gen_third_party_licenses.py from Cargo.lock",
        f"(Rust crates compiled for {TARGET}: {len(used) - 1}).",
        "",
    ]
    # Packages without a license file of their own: a dual MIT / Apache-2.0
    # crate is used here under Apache-2.0, whose full text is in this file;
    # the Boost license asks for no notice in machine-executable form.
    apache = [m for m in missing if "Apache-2.0" in m]
    boost = [m for m in missing if "BSL-1.0" in m and m not in apache]
    other = [m for m in missing if m not in apache and m not in boost]
    if apache:
        out += [
            "Used under the Apache License 2.0, whose full text appears below",
            "(these packages ship no license file of their own):",
            "",
        ] + [f"  - {m}" for m in apache] + [""]
    if boost:
        out += [
            "Boost Software License 1.0 (no notice required for distribution in",
            "machine-executable form):",
            "",
        ] + [f"  - {m}" for m in boost] + [""]
    if other:
        out += [
            "Packages without a license file (their declared license applies):",
            "",
        ] + [f"  - {m}" for m in other] + [""]
    if apache:
        assert any("Apache License" in g["text"] and "Version 2.0" in g["text"] for g in groups.values()), \
            "no Apache-2.0 text collected for the packages used under it"

    def block(title, files, text):
        out.extend(["", "-" * 78, title, f"File: {', '.join(sorted(files))}", "-" * 78, ""])
        if text == gpl_text:
            out.append("(GNU General Public License v3: same text as LICENSE.txt.)")
        else:
            out.append(text)
        out.append("")

    for title, path in EXTRA:
        block(title, [path.name], read(path))
    for g in sorted(groups.values(), key=lambda g: g["users"][0]):
        block("Used by: " + ", ".join(g["users"]), g["files"], g["text"])

    OUT.write_text("\n".join(out).rstrip("\n") + "\n", encoding="utf-8", newline="\n")
    print(f"{OUT.name}: {len(used) - 1} crates, {len(groups)} distinct texts, {len(missing)} without a file")


if __name__ == "__main__":
    main()
